### ISSUE TITLE
error

### ISSUE THREAD

**Issue by alikaptanoglu** [sureshpandiyan1/instagram-scraper-it#3]
instagram-scraper-it=LIVE :)
--------------------------
1 insta id
2 get complete data about the user
3 search the users
4 profile information (yours)
5 list all insta users
6 random fake users list
7 find similar hashtag
8 list of active story post (yours)
9 recent inbox online users (yours)
10 list all followings
11 unread message (yours)
12 get biography
13 analyze your post for growth
14 get any reels / image with complete data
15 collect anyone followers list
16 quit
choose your option => 15

choose your option => 15
Traceback (most recent call last):
  File "C:\Users\rssmo\Desktop\instagram-scraper-it-1.1.0\main.py", line 366, in <module>
    insta_svc()
  File "C:\Users\rssmo\Desktop\instagram-scraper-it-1.1.0\main.py", line 91, in insta_svc
    collect_anyone_followers_list()
  File "C:\Users\rssmo\Desktop\instagram-scraper-it-1.1.0\main.py", line 333, in collect_anyone_followers_list
    cnt_mx = followers_counts / 12
TypeError: unsupported operand type(s) for /: 'str' and 'int'

**Comment by sureshpandiyan1** [comment]
In followersid.py
your every value should be integer, but not a string

```
Example:
followers_counts = 100  
target_insta_id = 123456789
```

**Comment by alikaptanoglu** [comment]
thank you very nice job my mistake target_insta_id = 123456789
